# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python Library Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Test on ${{ matrix.os }}, python ${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: 
          - ubuntu-20.04
# Windows is broken
#          - windows-2019
          - macOS-10.15
        python:
          - 3.8
          - 3.9
          - 3.10
          - 3.11
          - "pypy3.8"
          - "pypy3.9"

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
  - name: Download wheels
    uses: actions/download-artifact@v3
    with:
      name: wheels
      path: ./wheels
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
    - name: Lint with flake8
      run: |
        flake8 . --count --show-source --statistics
    - name: Install self
      run: |
        pip install --find-links ./wheels secp256k1-py
    - name: Test with pytest
      run: |
        pytest
