name: Python Library Tests

on:
  workflow_run:
    workflows: [Build wheels]
    types:
      - completed

jobs:
  test:
    name: Test on Windows, python ${{ matrix.python }}
    runs-on: windows-2019
    strategy:
      matrix:
        python:
          - 3.8
          - 3.9
          - 3.10
          - 3.11
          - "pypy3.8"
          - "pypy3.9"

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Download wheels
      uses: actions/download-artifact@v3
      with:
        name: wheels
        path: ./wheels
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
    - name: Lint with flake8
      run: |
        flake8 . --count --show-source --statistics
    - name: Install self
      run: |
        pip install --find-links ./wheels secp256k1-py
    - name: Test with pytest
      run: |
        pytest
